/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export { }
declare global {
	const d: (typeof import('$/utils/debug'))['d'];
	const dt: (typeof import('$/utils/debug'))['dt'];
}
